### ISSUE TITLE
Issue in Requirements.txt within "chapter_2-1"

### ISSUE THREAD

**Issue by KuroOrb** [shogunlab/building-c2-implants-in-cpp#2]
The commands `pip install -r requirements.txt` errors out. This is because if you have setup a fresh Python environment, "**wheel**" is not installed. Most likely need to add `wheel` to the requirements or just `pip install wheel` before running the install command for `requirements.txt`. This is for Python version 3.8.16.

**Comment by shogunlab** [comment]
Thanks for the heads up! I've added instructions in Chapter 2 of the eBook to perform `pip install wheel` prior to issuing an install command.
